const { createKV, getSessionToken } = require('./_utils');
const { lookupPdfUrl } = require('./_form-urls');
const { PDFDocument } = require('pdf-lib');
const kv = createKV();

const ALLOWED_DOMAINS = [
  'irs.gov', 'uscis.gov', 'state.gov', 'eforms.state.gov', 'dol.gov', 'hhs.gov',
  'ed.gov', 'ssa.gov', 'va.gov', 'vba.va.gov', 'sba.gov', 'epa.gov', 'dhs.gov',
  'cbp.gov', 'ice.gov', 'fema.gov', 'opm.gov', 'ftc.gov', 'sec.gov',
  'treasury.gov', 'cms.gov', 'cdc.gov', 'usps.com', 'studentaid.gov',
];

function isAllowedUrl(raw) {
  try {
    const u = new URL(raw);
    if (u.protocol !== 'https:') return false;
    return ALLOWED_DOMAINS.some(d => u.hostname === d || u.hostname.endsWith('.' + d));
  } catch { return false; }
}

// ── Field-name matching ────────────────────────────────────────────────────

function norm(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]/g, '');
}

// Tokenise a field name into meaningful words
function tokens(s) {
  return String(s)
    .replace(/([a-z])([A-Z])/g, '$1 $2')     // camelCase split
    .replace(/[_\-./[\]()]/g, ' ')            // punctuation → space
    .toLowerCase()
    .split(/\s+/)
    .filter(t => t.length > 1);
}

function score(aiName, pdfName) {
  const an = norm(aiName), pn = norm(pdfName);
  if (an === pn) return 100;
  if (pn.includes(an) || an.includes(pn)) return 80;
  const at = tokens(aiName), pt = tokens(pdfName);
  const shared = at.filter(t => pt.includes(t)).length;
  if (shared === 0) return 0;
  return Math.round(60 * shared / Math.max(at.length, pt.length));
}

function bestMatch(aiName, pdfNames) {
  let best = null, bestScore = 30; // minimum threshold
  for (const p of pdfNames) {
    const s = score(aiName, p);
    if (s > bestScore) { best = p; bestScore = s; }
  }
  return best;
}

// ── Handler ────────────────────────────────────────────────────────────────

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();

  const token = getSessionToken(req);
  if (!token) return res.status(401).json({ error: 'auth_required' });

  const email = await kv.get(`session:${token}`);
  if (!email) return res.status(401).json({ error: 'session_expired' });

  const { pdfUrl, formName, fields } = req.body || {};

  // Resolve URL: curated map > caller-supplied > error
  let resolvedUrl = null;
  if (formName) {
    const curated = lookupPdfUrl(formName);
    if (curated === null) {
      return res.status(422).json({ error: 'This form has no downloadable PDF — it is submitted online or generated by an employer.' });
    }
    if (typeof curated === 'string') resolvedUrl = curated;
  }
  if (!resolvedUrl && pdfUrl) resolvedUrl = pdfUrl;
  if (!resolvedUrl) return res.status(400).json({ error: 'pdfUrl or formName is required' });

  if (!isAllowedUrl(resolvedUrl)) {
    return res.status(400).json({ error: 'Only official government PDF URLs are supported.' });
  }

  // ── Fetch PDF ────────────────────────────────────────────────
  let pdfBytes;
  try {
    const upstream = await fetch(resolvedUrl, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; FormIQ/1.0)' },
      redirect: 'follow',
    });
    if (!upstream.ok) {
      return res.status(502).json({
        error: `Could not download the official form (HTTP ${upstream.status}). The government may have moved the file.`,
        fallback_url: resolvedUrl,
      });
    }
    pdfBytes = new Uint8Array(await upstream.arrayBuffer());
  } catch (err) {
    return res.status(502).json({ error: 'Network error fetching form: ' + err.message });
  }

  // ── Load & inspect PDF ───────────────────────────────────────
  let pdfDoc;
  try {
    pdfDoc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });
  } catch (err) {
    return res.status(422).json({ error: 'Could not parse the PDF: ' + err.message });
  }

  const form = pdfDoc.getForm();
  const pdfFields = form.getFields();

  // Detect XFA (xml-based) forms — pdf-lib cannot fill these
  const isXfa = pdfFields.length === 0 && pdfBytes.includes
    && (function() {
      const chunk = Buffer.from(pdfBytes).slice(0, 8192).toString('binary');
      return chunk.includes('/XFA') || chunk.includes('xdp:xdp');
    })();

  if (pdfFields.length === 0) {
    const msg = isXfa
      ? 'This PDF uses the XFA format, which cannot be filled programmatically. Download the blank form and fill it manually in Adobe Acrobat or Adobe Reader.'
      : 'This PDF has no fillable fields. Download the blank form and fill it manually.';
    return res.status(422).json({ error: msg, fallback_url: resolvedUrl });
  }

  // ── Fill fields ──────────────────────────────────────────────
  let filled = 0;
  const pdfFieldNames = pdfFields.map(f => f.getName());

  if (Array.isArray(fields) && fields.length > 0) {
    for (const { field, value } of fields) {
      if (!field || value == null) continue;
      const match = bestMatch(field, pdfFieldNames);
      if (!match) continue;
      try {
        const pf = form.getField(match);
        const type = pf.constructor.name;
        const val = String(value);

        if (type === 'PDFTextField') {
          pf.setText(val);
          filled++;
        } else if (type === 'PDFCheckBox') {
          const v = val.toLowerCase();
          if (v === 'yes' || v === 'true' || v === 'x' || v === '1' || v === 'checked') {
            pf.check(); filled++;
          }
        } else if (type === 'PDFDropdown' || type === 'PDFOptionList') {
          const opts = pf.getOptions();
          const pick = opts.find(o => o.toLowerCase().includes(val.toLowerCase()))
                    || opts.find(o => val.toLowerCase().includes(o.toLowerCase()));
          if (pick) { pf.select(pick); filled++; }
        } else if (type === 'PDFRadioGroup') {
          const opts = pf.getOptions();
          const pick = opts.find(o => o.toLowerCase().includes(val.toLowerCase()));
          if (pick) { pf.select(pick); filled++; }
        }
      } catch (_) { /* read-only or incompatible field — skip silently */ }
    }
  }

  const out = await pdfDoc.save();

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename="filled-form.pdf"');
  res.setHeader('X-Fields-Filled', String(filled));
  res.setHeader('X-Fields-Total', String(pdfFields.length));
  return res.end(Buffer.from(out));
};
